# configuration.yaml
protein_tracker:
  users:
    - id: dashboard1
      name: Jon
      goal: 160
      calorie_goal: 2200
    - id: dashboard2
      name: Alex
      goal: 140
      calorie_goal: 2500
